<?php
/**
 * @package     Gamuza_Brazil
 * @copyright   Copyright (c) 2023 Gamuza Technologies (http://www.gamuza.com.br/)
 * @author      Eneias Ramos de Melo <eneias@gamuza.com.br>
 */
?>
<?php
/**
 * @see Mage_Payment_Block_Info
 */
?>
<p><strong><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></strong></p>

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
<table>
    <tbody>
    <?php foreach ($_specificInfo as $_label => $_value):?>
        <tr>
            <th><strong><?php echo $this->escapeHtml($_label)?>:</strong></th>
        </tr>
        <tr>
            <td><?php echo nl2br(implode("\n", $this->getValueAsArray($_value, false)))?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php endif;?>

<?php echo $this->getChildHtml()?>

<style>
#pix-payment-clear { clear: left; }
#pix-payment-response { max-width: 200px; margin: 20px; }
</style>

<div id="pix-payment-clear"></div>
<div id="pix-payment-response"></div>

<?php $_order = $this->_getOrder (); ?>
<?php if ($_order && $_order->getId ()): ?>

<?php $_qrCodeUrl = $this->_getQRCodeUrl ($_order->getId ()); ?>

<script type="text/javascript">
    new Ajax.Request ("<?php echo $_qrCodeUrl; ?>", {
        method: 'get',
        onSuccess: function (transport) {
            $('pix-payment-response').innerHTML = transport.responseText;

            new Effect.Appear ($('pix-payment-response'), {duration: 1});
        },
    });
</script>

<?php endif; ?>

