<?php
/**
 * @package     Gamuza_Basic
 * @copyright   Copyright (c) 2026 Gamuza Technologies (https://www.gamuza.com.br/)
 * @author      Eneias Ramos de Melo <eneias@gamuza.com.br>
 */
?>
<?php $_product = $this->getProduct(); ?>
<?php if ($_product->getAgeGate ()): ?>
<?php $_productAgeAmount = Mage::getStoreConfig(Gamuza_Basic_Helper_Data::XML_PATH_SALES_MINIMUM_AGE_AMOUNT); ?>
<p class="error">
<?php echo Mage::helper ('basic')->__('This product is restricted to adults %d years or older!', $_productAgeAmount); ?>
</p>
<?php if (Mage::getStoreConfigFlag (Gamuza_Basic_Helper_Data::XML_PATH_SALES_MINIMUM_AGE_ACTIVE)): ?>
<p class="age-gate">
<?php echo Mage::getStoreConfig(Gamuza_Basic_Helper_Data::XML_PATH_SALES_MINIMUM_AGE_DESCRIPTION); ?>
</p>
<p>
<?php echo Mage::getStoreConfig(Gamuza_Basic_Helper_Data::XML_PATH_SALES_MINIMUM_AGE_ERROR_MESSAGE); ?>
</p>
<?php endif; ?>
<?php endif; ?>

