<?php
/**
 * @package     Gamuza_Basic
 * @copyright   Copyright (c) 2023 Gamuza Technologies (https://www.gamuza.com.br/)
 * @author      Eneias Ramos de Melo <eneias@gamuza.com.br>
 */
?>
<input type="hidden" name="additional_options[0][code]" value="comment" />
<input type="hidden" name="additional_options[0][label]" value="<?php echo Mage::helper('basic')->__('Comment'); ?>" />
<textarea class="input-text form-control" name="additional_options[0][value]"
    placeholder="<?php echo Mage::helper('basic')->__('Comment'); ?>"
    title="<?php echo Mage::helper('basic')->__('Comment'); ?>"></textarea>

