<?php
/**
 * @package     Gamuza_Basic
 * @copyright   Copyright (c) 2026 Gamuza Technologies (https://www.gamuza.com.br/)
 * @author      Eneias Ramos de Melo <eneias@gamuza.com.br>
 */
?>

<script type="text/javascript">
$j(document).ready(function () {
    var brazilNCM  = $j("#brazil_ncm");
    var brazilCEST = $j("#brazil_cest");
    var brazilCFOP = $j("#brazil_cfop");

    if (brazilNCM  && brazilNCM.length)  brazilNCM.removeAttr("disabled");
    if (brazilCEST && brazilCEST.length) brazilCEST.removeAttr("disabled");
    if (brazilCFOP && brazilCFOP.length) brazilCFOP.removeAttr("disabled");

    $j('select.chosen-select').chosen({
        width: '100%',
        no_results_text: Translator.translate("No results match") + ":",
    });

    $j('select.chosen-select').closest('div.hor-scroll').removeClass('hor-scroll');
});
</script>

