<?php
/**
 * @package     Toluca_Express
 * @copyright   Copyright (c) 2023 Gamuza Technologies (https://www.gamuza.com.br/)
 * @author      Eneias Ramos de Melo <eneias@gamuza.com.br>
 */
?>
<script type="text/javascript">
productAddToCartForm.submit = function(url){
    if(this.validator && this.validator.validate()){
        var button = $j('.product-view .add-to-cart-buttons button.button');
        var form = $j(this.form);
        var message = undefined;

        button.attr('disabled', 'disabled');

        $j.ajax({
            url: form.attr('action'),
            type: form.attr('method'),
            enctype: form.attr('enctype'),
            data: form.serialize(),
        })
        .success(function(data) {
            message = "<?php echo Mage::helper('express')->__('Product was added to your shopping cart.'); ?>";

            productsModal.hide();
        })
        .fail(function(data){
            console.log(data);

            message = "<?php echo Mage::helper('express')->__('Cannot add item to the shopping cart.'); ?>";

            button.removeAttr('disabled');
        })
        .done(function(data){
            $j("<div>" + message + "</div>").dialog({
                modal: true,
                title: "<?php echo Mage::helper('express')->__('Cart'); ?>",
                buttons: [{text: "OK", click: function() { $j(this).dialog("close"); }}],
            });
        });
    }

    return false;
};
</script>

