<?php
/**
 * @package     Gamuza_Mobile
 * @copyright   Copyright (c) 2026 Gamuza Technologies (https://www.gamuza.com.br/)
 * @author      Eneias Ramos de Melo <eneias@gamuza.com.br>
 */

$_customer = $this->getCustomer();

echo sprintf('%s %s <b><u>%s</u></b>', $_customer->getFirstname(), $_customer->getLastname(), $_customer->getCellphone()) . PHP_EOL;

$_address = $_customer->getDefaultShippingAddress() ? $_customer->getDefaultShippingAddress() : $_customer->getDefaultBillingAddress();

echo sprintf('%s <b><u>%s</u></b> %s', $_address->getStreet1(), $_address->getStreet2(), $_address->getStreet3()) . PHP_EOL;
echo sprintf('%s %s', $_address->getStreet4(), $_address->getPostcode()) . PHP_EOL;
echo sprintf('%s %s %s', $_address->getCity(), $_address->getRegionCode(), $_address->getCountryId()) . PHP_EOL;
echo $this->getLineSeparator() . PHP_EOL;

$_orders = $this->getOrdersList();

echo Mage::helper('sales')->__('Total Orders Qty: %s', $_orders->getSize()) . PHP_EOL;

foreach ($_orders as $_order)
{
    echo $this->getLineSeparator($this->getOrderSequence($_order)) . PHP_EOL;

    $_subtotal = Mage::helper('core')->currency($_order->getBaseSubtotal(), true, false);
    $_shipping = Mage::helper('core')->currency($_order->getBaseShippingAmount(), true, false);
    $_fee      = Mage::helper('core')->currency($_order->getPayment()->getDeferredFeeAmount(), true, false);
    $_total    = Mage::helper('core')->currency($_order->getBaseGrandTotal(), true, false);

    echo sprintf('<b><u>%s</u></b> %s', $this->getOrderNumber($_order), $this->getOrderDatetime($_order)) . PHP_EOL;
    echo sprintf(
        "%s: %s\t%s: %s\n%s: %s\t%s: %s",
        Mage::helper('sales')->__('Subtotal'), $_subtotal,
        Mage::helper('sales')->__('Shipping Amount'), $_shipping,
        Mage::helper('sales')->__('Grand Total'), $_total,
        Mage::helper('sales')->__('Fee Amount'), $_fee,
    ) . PHP_EOL;
}

echo $this->getLineSeparator() . PHP_EOL;

$_subtotal = $this->getOrdersTotal ($_orders, 'base_subtotal');
$_shipping = $this->getOrdersTotal ($_orders, 'base_shipping_amount');
$_fee      = $this->getOrdersTotal ($_orders, 'deferred_fee_amount');
$_total    = $this->getOrdersTotal ($_orders, 'base_grand_total') + $_fee;

$_subtotal = Mage::helper('core')->currency($_subtotal, true, false);
$_shipping = Mage::helper('core')->currency($_shipping, true, false);
$_fee      = Mage::helper('core')->currency($_fee, true, false);
$_total    = Mage::helper('core')->currency($_total, true, false);

echo Mage::helper('sales')->__('Subtotal: %s', $_subtotal) . PHP_EOL;
echo Mage::helper('sales')->__('Shipping Amount: %s', $_shipping) . PHP_EOL;
echo Mage::helper('sales')->__('Fee Amount: %s', $_fee) . PHP_EOL;
echo Mage::helper('sales')->__('Grand Total: %s', $_total) . PHP_EOL;
echo $this->getLineSeparator() . PHP_EOL;

$_storeName  = Mage::getStoreConfig('general/store_information/name',  $_customer->getStoreId());
$_storePhone = Mage::getStoreConfig('general/store_information/phone', $_customer->getStoreId());

echo sprintf('%s %s', $_storeName, $_storePhone) . PHP_EOL;

echo sprintf('Toluca Store APP %s', Mage::getModel('core/date')->date('d/m/Y H:i:s')) . PHP_EOL . PHP_EOL;

?>
<cut>
